name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          repository: paybeehive/beehivehub-java-sdk
          path: beehivehub-java-sdk

      - name: Install SDK
        run: mvn install -DskipTests -f beehivehub-java-sdk/pom.xml

      - name: Build and test
        run: mvn verify
